# -*- coding: utf-8 -*-
"""cv_ocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YY341LkwUgyL5X0VP4hk8SPMB7BNNKd
"""

# Install required libraries
!apt install tesseract-ocr -y
!pip install opencv-python pytesseract imutils Pillow

# STEP 1: Upload
from google.colab import files
uploaded = files.upload()

# STEP 2: Install dependencies (for Colab)
!apt install tesseract-ocr -y
!pip install pytesseract opencv-python-headless google-generativeai --quiet

# STEP 3: Imports
import cv2
import numpy as np
import pytesseract
import matplotlib.pyplot as plt
from PIL import Image
import json
import google.generativeai as genai

# STEP 4: Tesseract Config
pytesseract.pytesseract.tesseract_cmd = "/usr/bin/tesseract"

# STEP 5: Load Image
img_path = list(uploaded.keys())[0]
img = cv2.imread(img_path)

# ✅ Configure Gemini API (replace with your own key)
genai.configure(api_key="AIzaSyC3n5gHWxAr-m5fCm_7xZvGZ25_tU8gzG0")
model = genai.GenerativeModel("models/gemini-1.5-pro")  # For pure text


# ----------- Utility Functions ------------

def preprocess_image(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    thresh = cv2.adaptiveThreshold(blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                   cv2.THRESH_BINARY_INV, 11, 3)
    return thresh

def extract_text_from_roi(roi):
    roi_gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    roi_blur = cv2.GaussianBlur(roi_gray, (3, 3), 0)
    roi_thresh = cv2.threshold(roi_blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
    text = pytesseract.image_to_string(roi_thresh, config='--psm 7').strip()
    return text

def gpt_label_suggestion(shape_type, raw_text):
    cleaned = raw_text.strip().replace('\n', ' ').replace('|', '').strip()

    if not cleaned or len(cleaned) < 2:
        return "Unknown"

    # Basic hardcoded fixes
    replacements = {
        'ff.': 'If',
        'Pag': 'Page',
        'n|': 'End',
        'pe a7': 'Read A',
        '‘bun': 'Run',
        ', |': ',',
        'i': 'Input',
        'N': 'No',
        '| : =': ':=',
        '|': ''
    }

    corrected = replacements.get(cleaned, cleaned)

    # Dynamic correction via Gemini
    try:
        prompt = f"The OCR text '{raw_text}' was extracted from a {shape_type} shape in a flowchart. Suggest a clean and appropriate label for it."
        response = model.generate_content(prompt)
        suggestion = response.text.strip()
        if suggestion and len(suggestion) < 20:
            return suggestion
        return corrected
    except Exception as e:
        print("❌ Gemini failed:", e)
        return corrected

def detect_shapes_and_text(thresh, image):
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    shapes_info = []

    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area < 300:
            continue

        approx = cv2.approxPolyDP(cnt, 0.04 * cv2.arcLength(cnt, True), True)
        x, y, w, h = cv2.boundingRect(approx)
        roi = image[y:y+h, x:x+w]

        shape_type = "unknown"
        color = (128, 128, 128)

        if len(approx) == 3:
            shape_type = "arrow"
            color = (0, 255, 255)
        elif len(approx) == 4:
            aspect_ratio = float(w) / h
            angles = []
            for i in range(4):
                p1 = approx[i][0]
                p2 = approx[(i+1) % 4][0]
                p3 = approx[(i+2) % 4][0]
                a = np.array(p1) - np.array(p2)
                b = np.array(p3) - np.array(p2)
                angle = np.arccos(np.dot(a, b) / (np.linalg.norm(a)*np.linalg.norm(b) + 1e-6))
                angles.append(np.degrees(angle))
            if all(70 < ang < 110 for ang in angles):
                shape_type = "process"
                color = (0, 255, 0)
            elif all(30 < ang < 150 for ang in angles) and not all(70 < ang < 110 for ang in angles):
                shape_type = "decision"
                color = (255, 0, 0)
            elif abs(aspect_ratio - 1) > 0.2:
                shape_type = "io"
                color = (255, 255, 0)
        elif len(approx) > 5:
            shape_type = "terminal"
            color = (255, 0, 255)

        raw_text = extract_text_from_roi(roi)
        cleaned_label = gpt_label_suggestion(shape_type, raw_text)

        cv2.drawContours(image, [cnt], -1, color, 2)
        cv2.putText(image, cleaned_label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        shapes_info.append({
            'type': shape_type,
            'raw_text': raw_text,
            'label': cleaned_label,
            'box': (x, y, w, h)
        })

    return image, shapes_info

# ----------- Execution ------------

if img is None:
    raise FileNotFoundError("❌ Image not found.")

thresh_img = preprocess_image(img)
result_img, shapes_data = detect_shapes_and_text(thresh_img, img.copy())

cv2.imwrite("final_flowchart_with_ocr.png", result_img)
print("✅ Final output saved as: final_flowchart_with_ocr.png")

print("\nDetected shapes with improved labels:")
for shape in shapes_data:
    print(f"{shape['type'].capitalize()} [{shape['label']}] <- OCR: {shape['raw_text']}")

# Save JSON
with open("shapes_data_with_labels.json", "w") as f:
    json.dump(shapes_data, f, indent=2)

# Display result
plt.figure(figsize=(10, 8))
plt.imshow(cv2.cvtColor(result_img, cv2.COLOR_BGR2RGB))
plt.title("Flowchart Detection + Gemini Labeling")
plt.axis('off')
plt.show()

# ----------- Optional: Generate pseudocode ------------

logic_prompt = f"Convert the following flowchart shapes and labels to pseudocode:\n\n{json.dumps(shapes_data, indent=2)}"
try:
    response = model.generate_content(logic_prompt)
    print("\n📜 Pseudocode from flowchart:")
    print(response.text.strip())
except Exception as e:
    print("❌ Gemini pseudocode generation failed:", e)

# STEP 1: Upload
from google.colab import files
uploaded = files.upload()

# STEP 2: Imports
import cv2
import numpy as np
import pytesseract
import matplotlib.pyplot as plt
from PIL import Image

pytesseract.pytesseract.tesseract_cmd = "/usr/bin/tesseract"


# STEP 3: Install tesseract in Colab
!apt install tesseract-ocr -y
!pip install pytesseract opencv-python-headless

# STEP 4: Use uploaded image
img_path = list(uploaded.keys())[0]  # Automatically use uploaded image
img = cv2.imread(img_path)

def preprocess_image(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    thresh = cv2.adaptiveThreshold(blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                   cv2.THRESH_BINARY_INV, 11, 3)
    return thresh

def detect_shapes_and_text(thresh, image):
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    shapes_info = []

    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area < 300:
            continue

        approx = cv2.approxPolyDP(cnt, 0.04 * cv2.arcLength(cnt, True), True)
        x, y, w, h = cv2.boundingRect(approx)
        roi = image[y:y+h, x:x+w]

        shape_type = "unknown"
        color = (128, 128, 128)

        if len(approx) == 3:
            shape_type = "arrow"
            color = (0, 255, 255)
        elif len(approx) == 4:
            aspect_ratio = float(w) / h
            if 0.9 <= aspect_ratio <= 1.1:
                shape_type = "process"
                color = (0, 255, 0)
            else:
                angles = []
                for i in range(4):
                    p1 = approx[i][0]
                    p2 = approx[(i+1) % 4][0]
                    p3 = approx[(i+2) % 4][0]
                    a = np.array(p1) - np.array(p2)
                    b = np.array(p3) - np.array(p2)
                    angle = np.arccos(np.dot(a, b) / (np.linalg.norm(a)*np.linalg.norm(b) + 1e-6))
                    angles.append(np.degrees(angle))
                if all(60 < ang < 130 for ang in angles):
                    shape_type = "decision"
                    color = (255, 0, 0)
                else:
                    shape_type = "io"
                    color = (255, 255, 0)
        elif len(approx) > 5:
            shape_type = "terminal"
            color = (255, 0, 255)

        text = pytesseract.image_to_string(roi, config='--psm 6').strip()
        cv2.drawContours(image, [cnt], -1, color, 2)
        label = f"{shape_type}: {text}"
        cv2.putText(image, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
        shapes_info.append({'type': shape_type, 'text': text, 'box': (x, y, w, h)})

    return image, shapes_info

# Process image
if img is None:
    raise FileNotFoundError("❌ Image not found.")

thresh_img = preprocess_image(img)
result_img, shapes_data = detect_shapes_and_text(thresh_img, img.copy())

# Save and show result
cv2.imwrite("final_flowchart_with_ocr.png", result_img)
print("✅ Final output saved as: final_flowchart_with_ocr.png")

print("\nDetected shapes with text:")
for shape in shapes_data:
    print(f"{shape['type'].capitalize()}: {shape['text']}")

# Show inline
plt.figure(figsize=(10, 8))
plt.imshow(cv2.cvtColor(result_img, cv2.COLOR_BGR2RGB))
plt.title("Flowchart Detection with OCR")
plt.axis('off')
plt.show()