# -*- coding: utf-8 -*-
"""flowchart_detection+ocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0h_K0ApVUgVHV_XreXruKWMHNkNNK5V
"""

# Install required libraries
!apt install tesseract-ocr -y
!pip install opencv-python pytesseract imutils Pillow

# STEP 1: Upload
from google.colab import files
uploaded = files.upload()

# STEP 2: Imports
import cv2
import numpy as np
import pytesseract
import matplotlib.pyplot as plt
from PIL import Image
import json

pytesseract.pytesseract.tesseract_cmd = "/usr/bin/tesseract"

# STEP 3: Install tesseract in Colab
!apt install tesseract-ocr -y
!pip install pytesseract opencv-python-headless

# STEP 4: Use uploaded image
img_path = list(uploaded.keys())[0]
img = cv2.imread(img_path)

# ----------- Utility Functions ------------

def preprocess_image(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    thresh = cv2.adaptiveThreshold(blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                   cv2.THRESH_BINARY_INV, 11, 3)
    return thresh

def extract_text_from_roi(roi):
    roi_gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    roi_blur = cv2.GaussianBlur(roi_gray, (3, 3), 0)
    roi_thresh = cv2.threshold(roi_blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
    text = pytesseract.image_to_string(roi_thresh, config='--psm 7').strip()
    return text

def detect_shapes_and_text(thresh, image):
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    shapes_info = []

    for cnt in contours:
        area = cv2.contourArea(cnt)
        if area < 300:
            continue

        approx = cv2.approxPolyDP(cnt, 0.04 * cv2.arcLength(cnt, True), True)
        x, y, w, h = cv2.boundingRect(approx)
        roi = image[y:y+h, x:x+w]

        shape_type = "unknown"
        color = (128, 128, 128)

        if len(approx) == 3:
            shape_type = "arrow"
            color = (0, 255, 255)

        elif len(approx) == 4:
            aspect_ratio = float(w) / h
            angles = []
            for i in range(4):
                p1 = approx[i][0]
                p2 = approx[(i+1) % 4][0]
                p3 = approx[(i+2) % 4][0]
                a = np.array(p1) - np.array(p2)
                b = np.array(p3) - np.array(p2)
                angle = np.arccos(np.dot(a, b) / (np.linalg.norm(a)*np.linalg.norm(b) + 1e-6))
                angles.append(np.degrees(angle))

            if all(70 < ang < 110 for ang in angles):
                shape_type = "process"
                color = (0, 255, 0)
            elif all(30 < ang < 150 for ang in angles) and not all(70 < ang < 110 for ang in angles):
                shape_type = "decision"
                color = (255, 0, 0)
            elif abs(aspect_ratio - 1) > 0.2:
                shape_type = "io"
                color = (255, 255, 0)

        elif len(approx) > 5:
            shape_type = "terminal"
            color = (255, 0, 255)

        text = extract_text_from_roi(roi)
        cv2.drawContours(image, [cnt], -1, color, 2)
        label = f"{shape_type}: {text}"
        cv2.putText(image, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
        shapes_info.append({'type': shape_type, 'text': text, 'box': (x, y, w, h)})

    return image, shapes_info

# ----------- Execution ------------

if img is None:
    raise FileNotFoundError("❌ Image not found.")

thresh_img = preprocess_image(img)
result_img, shapes_data = detect_shapes_and_text(thresh_img, img.copy())

cv2.imwrite("final_flowchart_with_ocr.png", result_img)
print("✅ Final output saved as: final_flowchart_with_ocr.png")

print("\nDetected shapes with text:")
for shape in shapes_data:
    print(f"{shape['type'].capitalize()}: {shape['text']}")

# Optional: Export structured data
with open("shapes_data.json", "w") as f:
    json.dump(shapes_data, f, indent=2)

# Show inline
plt.figure(figsize=(10, 8))
plt.imshow(cv2.cvtColor(result_img, cv2.COLOR_BGR2RGB))
plt.title("Flowchart Detection with OCR")
plt.axis('off')
plt.show()